### PR TITLE
improve grid.svg

### PR DESCRIPTION
**Pull request by etherrorcode404**
More familiar, Gnome's Dash to Dock like

### CODE REVIEW

**Comment by etherrorcode404** [comment]
This could be further advanced by changing a few colour settings, as majority may prefer a gnome shell like experience. However, all boils down to user preference. What do you think?

**Comment by nwg-piotr** [comment]
Well, I'm on vacation, with only an old laptop and a slow internet connection, but you seem to have changed 14 files. Check what's wrong with your PR, please.

image

**Comment by etherrorcode404** [comment]
well i ran a chmod +775

**Comment by etherrorcode404** [comment]
```
chmod +755 */* 
```

**Comment by etherrorcode404** [comment]
why?

**Comment by etherrorcode404** [comment]
it allows user to modify files without requiring root

**Comment by nwg-piotr** [comment]
You want to change a single file, right? Do whatever you want on your machine, but not on the repo.

**Comment by etherrorcode404** [comment]
Alright, in that case I'll make more changes which you can review later and leave file permission as it is

**Pull request closed without merging**
