### PR TITLE
gtk3 from diamondburned 

### PR DESCRIPTION
**Pull request by MaiorDomus**
Hi 

I was trying to find a way to stop the crashing that happened every now and then. The crashes that happened on my machine were unfortunately happening in the gtk code.. So I tried migrating the codebase to these newer bindings:
https://github.com/diamondburned/gotk4 and https://github.com/diamondburned/gotk4-layer-shell

Since migrating I haven't seen another crash, so might be worth switching?
It also seems to be a bit more responsive

### CODE REVIEW

**Comment by MaiorDomus** [comment]
Oh and here is a log file of one of the crashes (they all look the same): [nwg-dock-hyprland.log](https://github.com/user-attachments/files/17882688/nwg-dock-hyprland.log). These seem to be gone now (been running this version since 3 nov)

**Comment by nwg-piotr** [comment]
I'm feeling a bit confused. Is it gtk3 or 4?

**Comment by MaiorDomus** [comment]
The repository contains both, but I've used the gtk3 part. 

4 Would need a bit more effort since quite a lot of things changed under the hood (I did look into it a bit ;)
Should be easier to eventually migrate from this repo though, AFAIK it's the only one that supports gtk4 for go

**Comment by nwg-piotr** [comment]
Yeah, I'm not ready to migrate to GTK3, for several reasons.

The dock seems to behave perfectly well. Give me some time, please, to get a bit familiar withe the new library.

**Comment by MaiorDomus** [comment]
Sure no problem, thanks for taking a look at it!

**Comment by nwg-piotr** [comment]
Sorry that it takes so long, but migration makes sense to me only if I can migrate all my gtk/golang-based stuff. I took me 4 evenings or so, but now I have nwg-drawer built over the new library and ready for testing. If it turns out stable enough, we'll have 2 out of 5 items migrated - a good start. :D

**Comment by MaiorDomus** [comment]
Makes perfect sense, take your time! :)
Fingers crossed that it works with all 5

**Comment by nwg-piotr** [comment]
As for the new version of nwg-drawer, I'm still unsure, but it's time make a decision, as I have some further work on the dock planned. Let's merge both, if so.

**Pull request merged**
